### ISSUE TITLE
Could you open source your data processing code?

### ISSUE THREAD

**Issue by CindyTing** [zychen423/UHop#5]
Hello author, could you open source your data processing code? Or could you provide ideas for data processing? I want to apply it to other datasets, but for the data processing part, I don’t know how to implement it. Thank you very much.

**Comment by zychen423** [comment]
Hi @CindyTing , 

Sorry that I cannot give you the code of data preprocess. However I think the procedure is really simple. You just have to traverse your KG, and list all the path (including the correct one and the incorrect ones) in different hop. And as I remember the data format is something like

```
[question_id, 
question_text, 
[
  (correct_path_in_hop_1, 1), (incorrect_path_in_hop_1, 0), (incorrect_path_in_hop_1, 0), (incorrect_path_in_hop_1, 0)], 
  [(correct_path_in_hop_2, 1), (incorrect_path_in_hop_2, 0), (incorrect_path_in_hop_2, 0), (incorrect_path_in_hop_2, 0)], 
 [ (incorrect_path_in_hop_3, 0), (incorrect_path_in_hop_3, 0), (incorrect_path_in_hop_3, 0)]
]
```
Assuming that the correct answer can be found in the second hop.

Hope this will help!

**Comment by CindyTing** [comment]
Thank you very much for your reply.
